#!/bin/sh

set -e

update-alternatives --install /usr/lib/aarch64-linux-gnu/libblas.so libblas.so-aarch64-linux-gnu \
                    /usr/lib/aarch64-linux-gnu/blas/libblas.so 10 \
                    --slave /usr/lib/aarch64-linux-gnu/libblas.a libblas.a-aarch64-linux-gnu \
                    /usr/lib/aarch64-linux-gnu/blas/libblas.a \
                    --slave /usr/include/aarch64-linux-gnu/cblas.h cblas.h-aarch64-linux-gnu \
                    /usr/include/aarch64-linux-gnu/cblas-netlib.h \
                    --slave /usr/lib/aarch64-linux-gnu/pkgconfig/blas.pc \
                    blas.pc-aarch64-linux-gnu /usr/lib/aarch64-linux-gnu/pkgconfig/blas-netlib.pc



exit 0
